name = "mfng"
main = "../../../dist/main-worker.js"
compatibility_date = "2023-02-21"

[dev]
port = 3000

# Deactivate build command to prevent wrangler from restarting the build on any
# code change. Instead we start the build separately (in watch mode).
[build]
command = ""
watch_dir = []

[assets]
bucket = "../../../dist"
include = ["client", "react-ssr-manifest"]
serve_single_page_app = true

[[services]]
binding = "RSC"
service = "mfng-rsc"
